export const LanguageKeys = [
  'fillCorrectlyWithName',
  'inputIsRequiredWithName',
  'by',
  'blog',
  'categories',
  'authors',
  'previous',
  'next',
  'blogFoundMessageWithVariable',
  'showMore',
  'blogsYouMightLike',
  'subscribeSuccessMessageWithVariable',
  'weWillNeverShareYourEmail',
  'category',
  'author',
  'search',
] as const;
